spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    add-mappings: true 
    static-locations: classpath:/static/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/db;AUTO_SERVER=true
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: create-drop