spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /dist/**
  resources:
    add-mappings: true 
    static-locations: classpath:/dist/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/db;AUTO_SERVER=true
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
---

spring: 
  profiles: prod
  datasource:
    url: jdbc:h2:./data/db
  h2:
    console:
      enabled: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false