spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    add-mappings: true 
    static-locations: classpath:/static/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:../data/db;AUTO_SERVER=true
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: update
logging:
  path: ./logs/application.log
  file:
    max-size: 1GB
  pattern:
    file: "[%d{YYYY-MM-dd HH:mm:ss}] [%-5p] [%F:%L] %m%n"
  level:
    root: WARN
    org.springframework: ERROR
    com.ryum: INFO