spring:
  profiles:
    active: dev
  thymeleaf:    prefix: classpath:/public/
  mvc:
    static-path-pattern: /static/**
  resources:
    add-mappings: true 
    static-locations: classpath:/static/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/db;AUTO_SERVER=true
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /console
logging:
  config: classpath:logback.xml
  
---

spring: 
  profiles: prod
  datasource:
    url: jdbc:h2:../data/db 
  h2:
    console:
      enabled: false